# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nj6Xuhxu3m3-7k8qavCHK_BYjm5vD_lW
"""

!pip install streamlit
!pip install protobuf==3.20.0

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Congratulations!")
# st.header("You've just created a website")
# st.balloons()
# st.snow()

!streamlit run app.py & npx localtunnel --port 8501